services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_container
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=bookymyscreendbpass
      - POSTGRES_DB=bookymyscreendb
    networks:
      - monorepo-network
    volumes:
      - monorepo-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis_container
    restart: always

    ports:
      - "6379:6379"

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - monorepo-network

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
      args:
        DATABASE_URL: postgresql://postgres:mydbpass@postgres:5432/mydockerdb
    container_name: backend-container
    ports:
      - 4000:4000
    env_file:
      - apps/backend/.env.docker
    networks:
      - monorepo-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    container_name: frontend-container
    ports:
      - 3000:3000
    networks:
      - monorepo-network
    depends_on:
      backend:
        condition: service_started

networks:
  monorepo-network:

volumes:
  monorepo-volume:
