name: Lint Code

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install pnpm dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate the prisma client and db build
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: pnpm run db:generate && pnpm run db:build

      - name: Run Lint
        run: pnpm turbo run lint
